/*RUN FROM SIDE BY SIDE DATAPC*/
SET ECHO ON
CREATE DATABASE LINK "DB.DATA-PC02"
CONNECT TO ljc878
IDENTIFIED BY B4Baa4 USING 'data-pc02';

CREATE SYNONYM PC2EMP FOR EMPLOYEE@"DB.DATA-PC02";
CREATE SYNONYM PC2DRIVER FOR DRIVER@"DB.DATA-PC02";
CREATE SYNONYM PC2ADMIN FOR ADMIN@"DB.DATA-PC02";
CREATE SYNONYM PC2TRUCK FOR TRUCK@"DB.DATA-PC02";
CREATE SYNONYM PC2TRIP FOR TRIP@"DB.DATA-PC02";
CREATE SYNONYM PC2TLEG FOR TRIPLEG@"DB.DATA-PC02";
CREATE SYNONYM PC2SKILL FOR SKILL@"DB.DATA-PC02";
CREATE SYNONYM PC2SREQUIRED FOR SKILLREQUIRED@"DB.DATA-PC02";
CREATE SYNONYM PC2SPOSSESED FOR SKILLPOSSESSED@"DB.DATA-PC02";

create table EMPLOYEE as 
	select * 
	from PC2EMP 
	where 1=0;
INSERT INTO EMPLOYEE 
	SELECT *
	FROM PC2EMP 
	WHERE (PC2EMP.STATE = 'Vic' OR PC2EMP.STATE = 'WA'OR PC2EMP.STATE = 'Tas');

create table DRIVER as 
select * from PC2DRIVER where 1=0;
INSERT INTO DRIVER 
	SELECT *
	FROM PC2DRIVER 
	WHERE EXISTS(SELECT *
				 FROM EMPLOYEE E
				 WHERE E.E# = PC2DRIVER.E#);

create table ADMIN as 
select * from PC2ADMIN where 1=0;
INSERT INTO ADMIN 
	SELECT *
	FROM PC2ADMIN;
create table TRUCK as 
select * from PC2TRUCK where 1=0;
INSERT INTO TRUCK 
	SELECT *
	FROM PC2TRUCK;
create table TRIP as 
select * from PC2TRIP where 1=0;
INSERT INTO TRIP
	SELECT *
	FROM PC2TRIP
	WHERE EXISTS(SELECT * 
				 FROM DRIVER
				 WHERE PC2TRIP.L# = DRIVER.L#);

create table TRIPLEG as 
select * from PC2TLEG where 1=0;
INSERT INTO TRIPLEG 
	SELECT *
	FROM PC2TLEG
	WHERE EXISTS(SELECT *
				 FROM TRIP
				 WHERE PC2TLEG.T# = TRIP.T#);

create table SKILL as 
select * from PC2SKILL where 1=0;
INSERT INTO SKILL
	SELECT *
	FROM PC2SKILL;
create table SKILLREQUIRED as 
select * from PC2SREQUIRED where 1=0;
INSERT INTO SKILLREQUIRED
	SELECT *
	FROM PC2SREQUIRED; 
create table SKILLPOSSESED as 
select * from PC2SPOSSESED where 1=0;
INSERT INTO SKILLPOSSESED
	SELECT *
	FROM PC2SPOSSESED 
	WHERE EXISTS(SELECT *
				 FROM EMPLOYEE
				 WHERE EMPLOYEE.E# = PC2SPOSSESED.E#);


DELETE FROM	PC2SPOSSESED
WHERE EXISTS(SELECT *
			 FROM EMPLOYEE
			 WHERE EMPLOYEE.E# = PC2SPOSSESED.E#);			 
DELETE FROM	PC2TRIP
WHERE EXISTS(SELECT * 
				 FROM DRIVER
				 WHERE PC2TRIP.L# = DRIVER.L#);
DELETE FROM	PC2DRIVER
WHERE EXISTS(SELECT *
				 FROM EMPLOYEE
				 WHERE EMPLOYEE.E# = PC2DRIVER.E#);
DELETE FROM PC2ADMIN
WHERE EXISTS(SELECT *
			FROM EMPLOYEE
			WHERE EMPLOYEE.E# = PC2ADMIN.E#);
DELETE FROM	PC2EMP
WHERE EXISTS(SELECT *
			FROM EMPLOYEE
			WHERE EMPLOYEE.E# = PC2EMP.E#);
