SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

UPDATE POSITION 
SET Salary = Salary * 0.10
WHERE EXISTS (SELECT ename
			  FROM EMPLOYER
			  WHERE Employer.ename = Position.ename AND Employer.state = 'New South Wales' );

DECLARE
SYSTS VARCHAR(60);

BEGIN
 SELECT TO_CHAR(SYSTIMESTAMP)
 INTO SYSTS
 FROM DUAL;

DBMS_OUTPUT.PUT_LINE(SYSTS);

DBMS_LOCK.SLEEP(10);         /* Sleep for 10 seconds						*/

SELECT TO_CHAR(SYSTIMESTAMP)
INTO SYSTS
FROM DUAL;

DBMS_OUTPUT.PUT_LINE(SYSTS);
END;			  
/
COMMIT;