SPOOL dbdrop
SET ECHO ON
SET FEEDBACK ON

DROP TABLE SKILLREQUIRED PURGE;
DROP TABLE SKILLPOSSESSED PURGE;
DROP TABLE SKILL PURGE;
DROP TABLE TRIPLEG PURGE;
DROP TABLE TRIP PURGE;
DROP TABLE DRIVER PURGE;
DROP TABLE ADMIN PURGE;
DROP TABLE TRUCK PURGE;
DROP TABLE EMPLOYEE PURGE;

PROMPT Done.
SPOOL OFF
