SPOOL dbdrop
SET ECHO ON
SET LINESIZE 200
SET WRAP OFF

DROP TABLE APPLIES PURGE;
DROP TABLE SNEEDED PURGE;
DROP TABLE POSITION PURGE;
DROP TABLE SPOSSESSED PURGE;
DROP TABLE EMPLBY PURGE;
DROP TABLE EMPLOYER PURGE;
DROP TABLE APPLICANT PURGE;
DROP TABLE SKILL PURGE;

PROMPT Done.
SPOOL  OFF
